SAMPLE=QCD_HT2000toInf             ; ./condor_scripts/condor_test.py 50  "./main -c configs/config.txt -u cut1 -d ~/data/condor_output/$DATE/histos -l $TAG -s $SAMPLE -n  10"
SAMPLE=QCD_HT1500to2000            ; ./condor_scripts/condor_test.py 50  "./main -c configs/config.txt -u cut1 -d ~/data/condor_output/$DATE/histos -l $TAG -s $SAMPLE -n  10"
SAMPLE=QCD_HT1000to1500            ; ./condor_scripts/condor_test.py 50  "./main -c configs/config.txt -u cut1 -d ~/data/condor_output/$DATE/histos -l $TAG -s $SAMPLE -n  10"
SAMPLE=QCD_HT700to1000             ; ./condor_scripts/condor_test.py 50  "./main -c configs/config.txt -u cut1 -d ~/data/condor_output/$DATE/histos -l $TAG -s $SAMPLE -n  10"
SAMPLE=QCD_HT500to700              ; ./condor_scripts/condor_test.py 50  "./main -c configs/config.txt -u cut1 -d ~/data/condor_output/$DATE/histos -l $TAG -s $SAMPLE -n  10"
